version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - C:\Users\amula\Desktop\Alexandre\VSC\Hexagone\DevOps:/var/www/html
      - .env:/var/www/html/.env  # Monte le fichier .env dans le conteneur
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - my_network

  # Service MongoDB
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb-data:/data/db  # Ajout du volume

networks:
  my_network:
    driver: bridge

volumes:
  mongodb-data: